site_name: SDD
site_description: Statistical Foundations of Machine Learning section of the Algorithms in Machine Learning class at ISAE-Supaero
site_url: https://supaerodatascience.github.io/stat-ml/
site_dir: site
strict: false
use_directory_urls: false

theme:
  name: 'material'
  palette:
    primary: light blue
    accent: light blue
  logo: 'https://raw.githubusercontent.com/SupaeroDataScience/stat-ml/main/src/favicon.ico'
  favicon: 'https://raw.githubusercontent.com/SupaeroDataScience/stat-ml/main/src/favicon.ico'
  features:
    - toc.autohide
    - navigation.sections

repo_name: SupaeroDataScience/stat-ml
repo_url: https://github.com/SupaeroDataScience/stat-ml


nav:
- Home: https://supaerodatascience.github.io/index.html

- Classes:
  - Fundamentals of Decision Making: 
    - Overview: https://supaerodatascience.github.io/310/index.html
    - Data Engineering Fundamentals: https://supaerodatascience.github.io/310/ctf.html
    - Statistical Models: index.md
    - Optimization: https://supaerodatascience.github.io/310/opti.html
  
  - Machine Learning: https://supaerodatascience.github.io/aml.html

  - Data Engineering: https://supaerodatascience.github.io/DE/

  - Applied Data Science: https://supaerodatascience.github.io/313/index.html

  - Seminars: https://supaerodatascience.github.io/seminars.html

- Resources:
  - For current students: https://supaerodatascience.github.io/infostudents.html
  - For prospective students: https://supaerodatascience.github.io/students.html
  - For partners: https://supaerodatascience.github.io/partners.html
  - Contact: https://supaerodatascience.github.io/contact.html


markdown_extensions:
- markdown.extensions.codehilite:
    guess_lang: false
- toc:
    permalink: 🔗
- admonition
- codehilite
- extra
- attr_list
- pymdownx.details
- pymdownx.superfences

plugins:
- search
